### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by silentFred** [wilmoore/selectn.js#19]
Hey man,

Would you mind creating a new release?

Cheers

**Comment by wilmoore** [comment]
Sorry for the delay: https://github.com/wilmoore/selectn.js/releases/tag/v0.10.0

**Comment by MarkHerhold** [comment]
@wilmoore Thanks for the release. Could you update History.md with what changed changed?

Many thanks!

**Comment by wilmoore** [comment]
@MarkHerhold done :)

**Comment by MarkHerhold** [comment]
:+1:
