### ISSUE TITLE
Failing on undefined param

### ISSUE THREAD

**Issue by mlarcher** [wilmoore/selectn.js#21]
When calling selectn with an undefined param as in `selectn({}.missingProperty, {}))`, selectn fails to find the replace method and throws a nasty error.
Considering that we may use it with data coming from an API that may not be present yet, it seems a bit over the top to stop all code in the event loop for such a minor issue.
Could you please add a guard to prevent that error from happening in such case ?

**Comment by wilmoore** [comment]
HI @mlarcher,

Thanks for taking the time to report this. I've looked into it and I have a solution which I'll be working on shortly.

Thanks!
