### ISSUE TITLE
Test when value is 'null'

### ISSUE THREAD

**Issue by emanuelef** [wilmoore/selectn.js#24]
Hi,
I'm trying to access an object where a property is null, in that case there's a TypeError: Cannot read property 'body' of null.
Is it the expected behaviour ?
Thanks

**Comment by wilmoore** [comment]
Hi @emanuelef,

Thanks for reporting the issue. I suspect that you may be using an older version of `selectn` as this sounds very similar to a previous bug report that I've recently fixed.

Below is a link to the closed issue:

https://github.com/wilmoore/selectn.js/issues/21

Also, below is a link to a tonicdev notebook that you can run in your browser to test that things are working as they should be in the latest version:

https://tonicdev.com/wilmoore/56b14c8b5731b50d00f57e4e

**Comment by emanuelef** [comment]
Hi,
thanks for replying.

This is what I do:

```
var selectn = require('selection
var data = { value: null }
selectn(['value', 'test'], data)
```
I would expect to get undefined but I get: Type Error

[#24](https://tonicdev.com/emafuma/selectn)

**Comment by wilmoore** [comment]
Thanks for the updated information @emanuelef. This has been corrected and will be in the next patch release.
