### ISSUE TITLE
Supporting keys with a dot

### ISSUE THREAD

**Issue by dremekie** [wilmoore/selectn.js#25]
Hi. Would there be a way to handle key names with "." in it?

Example
```json
{
  "person": {
    "first.name": "Dwayne",
    "last.name": "Edward"
  }
}
```

Obviously, `person.first.name` will not work since the "." is used to traverse the object hierarchy and does not know that `first.name` is a key onto itself.

**Comment by wilmoore** [comment]
Hi @dremekie,

Thanks for trying out my lib. You can actually get to your dot-notation property if you use the fairly undocumented feature of passing an array instead of a string as path.

```js
selectn(['person', 'first.name'], data)
// => 'Dwayne'
```

**Comment by dremekie** [comment]
Aah! Thanks.

**Comment by wilmoore** [comment]
Thanks again @dremekie -- an example has been added to version 1.0.6: https://github.com/wilmoore/selectn.js/tree/v1.0.6#support-for-keys-containing-
