### ISSUE TITLE
Workability with React Native

### ISSUE THREAD

**Issue by vishysank** [wilmoore/selectn.js#61]
Hey man, 

I love this module, and use it on almost all of my projects. However, I noticed that when I try to use this package with react native, it causes an error. Do you know if it is possible to get this working with react -native ?
<img width="373" alt="screen shot 2017-02-04 at 10 10 38 pm" src="https://cloud.githubusercontent.com/assets/9473390/22623870/dd598256-eb26-11e6-9948-98564882b6f6.png">

**Comment by wilmoore** [comment]
Hey man. Glad you are trying this w/ react-native. I just ran through the [getting started guide](https://facebook.github.io/react-native/docs/getting-started.html) to create the default project, then I did `npm install --save selectn` and the project was able to build without issue.

A couple things to try:

```
rm -rf node_modules
yarn
react-native run-ios
```

If that doesn't work, please paste the output of `npm version`

**Comment by wilmoore** [comment]
Also, the import statement should be:

```
import selectn from 'selectn';
```

**Comment by vishysank** [comment]
my bad yeah it works now, thanks man

**Comment by wilmoore** [comment]
Of course...anytime man!
