### ISSUE TITLE
Support dots in name at any point

### ISSUE THREAD

**Issue by Nokel81** [wilmoore/selectn.js#78]
What would be really nice is if the follow could be done:

```js
var obj = {
    'a.b': {
        'c': 5
    }
};

selectn('a.b.c', obj, {tryEverything: true });
// => 5
```

With `tryEverything` enabled (or something similar) then it would so a sort of "smart" search through the object, greedily trying to find the path to the object. Namely, `a` is not found so it then tries `a.b` which is finds and then goes onto find `c`. Would this be something that this library might want to support?

**Comment by wilmoore** [comment]
Hey @Nokel81 - I LOVE the idea of the suggested functionality.

That being said, it is not a feature that keeps with the spirit of the original design of `selectn`. If you (or anyone else reading this) know of or decide to create such a lib, feel free to link it here as I could imagine use cases for such a tool.

❤️

**Comment by Nokel81** [comment]
Here you are: https://www.npmjs.com/package/dotfind

If you think anything should be added just open an issue on github

**Comment by Nokel81** [comment]
I created it because I had looked through libs and could not find one that did this

**Comment by Nokel81** [comment]
Since you thought that this would be useful would you mind adding it to the list of related packages?
